### ISSUE TITLE
CopyObject is not supported

### ISSUE THREAD

**Issue by lowpast** [awsdocs/amazon-s3-developer-guide#102]
Please update the documentation to **explicitly** call out that CopyObject is not a supported operation when using AccessPoints. This is not a stated limitation https://docs.aws.amazon.com/AmazonS3/latest/dev/access-points-restrictions-limitations.html and is also not explicitly stated in https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html#access-points-service-api-support

**Comment by rabilahiri** [comment]
Hi there,
Thanks for the feedback. S3 recently added support for CopyObject via access points: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-s3-access-points-now-support-copy-api/

Best,
Rabi Lahiri
Sr. Technical Writer, AWS
