### ISSUE TITLE
Replaced target by source bucket

### ISSUE THREAD

**Issue by AshishJainMSRIT** [awsdocs/amazon-s3-developer-guide#109]
In the heading "Querying Amazon S3 access logs for requests using Amazon Athena" in the first note box, the explanation should be "target bucket name and target prefix". As the source bucket's logs are present in the target bucket and we are querying target bucket in Athena.

This error occur in page: https://docs.aws.amazon.com/AmazonS3/latest/dev/using-s3-access-logs-to-identify-requests.html#querying-s3-access-logs-for-requests

**Comment by panjws** [comment]
You are right. 
Thanks! Your feedback helps us improve our docs for all.
We will correct and resolve this shortly. 
Best Regards and thanks for being an AWS customer.
