### ISSUE TITLE
CORS configuration in new S3 console is written ONLY in English document.

### ISSUE THREAD

**Issue by yutaro1985** [awsdocs/amazon-s3-developer-guide#119]
In new S3 console, CORS configuration must be JSON and we can't use old XML configuration.
But we can't find this in document except for English.
- English
https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

And can't find it in this repository.
What should we do to fix the document?

**Comment by aws-alan** [comment]
This page has been updated.
