### ISSUE TITLE
Typo though text not found in github

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-s3-developer-guide#23]
Hi there's a typo at:
https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html
"There are costs associated with the lifecycle transistion requests. For pricing information, see Amazon S3 Pricing."
Notice transistion > transition
But this text isn't on github, rest of page is.

**Comment by RandyOcheltree** [comment]
Thank you for reporting this error. It's fixed.
