### ISSUE TITLE
Duplicate / Incorrect link targets

### ISSUE THREAD

**Issue by seangreathouse** [awsdocs/amazon-s3-developer-guide#27]
[How much does it cost to retrieve data from Glacier?](https://aws.amazon.com/s3/faqs/#How_am_I_charged_for_deleting_objects_from_Amazon_Glacier_that_are_less_than_3_months_old)

+  [ How much does it cost to retrieve data from Glacier?](https://aws.amazon.com/s3/faqs/#How_am_I_charged_for_deleting_objects_from_Amazon_Glacier_that_are_less_than_3_months_old)

**Comment by RandyOcheltree** [comment]
Thank you for your feedback.
The issue you are describing is for the Amazon S3 FAQ.
Please only report issues here that apply to the Amazon S3 Developer Guide,

**Comment by seangreathouse** [comment]
Look at the link targets in the text below in this document:
lifecycle-transition-general-considerations.md

https://github.com/awsdocs/amazon-s3-developer-guide/blob/94bf60566adbf64e46c53a133cfd49c8cf70213a/doc_source/lifecycle-transition-general-considerations.md

"Glacier data restore charges—Amazon Glacier is designed for long-term archival of data that you will access infrequently. For information on data restoration charges, see How much does it cost to retrieve data from Glacier? in the Amazon S3 FAQ. For information on how to restore data from Glacier, see Restoring Archived Objects.

"When you archive objects to Amazon Glacier by using object lifecycle management, Amazon S3 transitions these objects asynchronously. There might be a delay between the transition date in the lifecycle configuration rule and the date of the physical transition. You are charged Amazon Glacier prices based on the transition date specified in the rule.

The Amazon S3 product detail page provides pricing information and example calculations for archiving Amazon S3 objects. For more information, see the following topics:

How is my storage charge calculated for Amazon S3 objects archived to Amazon Glacier?
How am I charged for deleting objects from Amazon Glacier that are less than 3 months old?
How much does it cost to retrieve data from Glacier?
Amazon S3 Pricing for storage costs for the Standard and GLACIER storage classes."
