### ISSUE TITLE
S3 CRR Replication Policy Invalid for new schema

### ISSUE THREAD

**Issue by miztiik** [awsdocs/amazon-s3-developer-guide#45]
In this doc: https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/crr-walkthrough-4.md

For `replication.json`, The schema is currently invalid as is,

- Priority should be int but it is str as of now
- Setting (overlapping)priorities is supported in new schema
-- This also means `DeleteMarkerReplication` will become invalid.

The document should either be updated for the new schema and encourage users to upgrade to new schema or call out that, it is using older schema

**Comment by jpmontez** [comment]
Yes the documentation on this page is very incorrect: https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-add-config.html

You must specify a `Prefix`, an int for `Priority`, and must remove the `DeleteMarkerReplication` as it's invalidated. The same information is invalid via the `aws-cli` tool. It's ridiculous that this isn't documented correctly, as all subsequent documentation is incorrect as well.

**Comment by aws-alan** [comment]
Replication walkthrough has been re-written. Thank you for bringing this to our attention.
