### ISSUE TITLE
Access to a deleted object in a versioned bucket in S3 returns 403 rather than 404

### ISSUE THREAD

**Issue by ali-tayebi** [awsdocs/amazon-s3-developer-guide#49]
The documentation at https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectVersioning.html is incompatible with S3 Get behaviour for a deleted object which resides in versioning enabled bucket (with Delete Marker). It returns **403** Forbidden rather than **404**

The following screenshot shows access to the current version (which is marked as deleted) is returning 403 (and not 404) while the previous version is accessible as expected.

<img width="987" alt="Screen Shot 2019-03-23 at 2 27 50 pm" src="https://user-images.githubusercontent.com/4958087/54861121-3d37eb80-4d78-11e9-8830-c4a373a01671.png">

**Comment by panjws** [comment]
Thanks for flagging. 
This has now been addressed.
