### ISSUE TITLE
Build script to PDF/HTML plus Kindle format?

### ISSUE THREAD

**Issue by petrabarus** [awsdocs/amazon-s3-developer-guide#5]
Hi all,

Thank you for AWS team who provides this. I really appreciate you working on this. I don't know where to post the issue but S3 is my favorite service so I think I just posted this.

I am wondering if it's also possible that you provide the build script as well to output the docs to PDF/HTML format. Plus if it also possible, Kindle format. I am having a problem downloading the Kindle format of the docs at Amazon Kindle store due to country restrictions.

Regards,

**Comment by AWSRandall** [comment]
Hello. Thanks for using S3!

I'm going to do some research and get back to you about the country restrictions. Thanks for letting us know!

Is it Indonesia you're asking about (if you don't mind me asking)?

**Comment by petrabarus** [comment]
Yes, it's for Indonesia. I hope I can download the documents from Amazon Kindle store. Thanks for looking at this.




--


Sent from my phone







On Wed, Mar 14, 2018 at 11:12 AM +0700, "Randall Isenhour" <notifications@github.com> wrote:












Hello. Thanks for using S3!


I'm going to do some research and get back to you about the country restrictions. Thanks for letting us know!


Is it Indonesia you're asking about (if you don't mind me asking)?
