### ISSUE TITLE
Typo in Host param of Virtual Hosted-Style request snippet

### ISSUE THREAD

**Issue by aksain** [awsdocs/amazon-s3-developer-guide#51]
In section "Example Virtual Hosted–Style Request' of page- "https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/RESTAPI.md", HOST parameter is shown as "examplebucket.s3-us-west-2.amazonaws.com" in sample request. 

Should it not be "examplebucket.s3.amazonaws.com" as virtual hosted-styled request Host doesn't need to have region information as per documentation?

**Comment by joeholl** [comment]
Fixed!
