### ISSUE TITLE
C++ mentioned in production docs, but not in this repo

### ISSUE THREAD

**Issue by mrichman** [awsdocs/amazon-s3-developer-guide#52]
"AWS SDK for C++;" (including semicolon typo) in production: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html

absent from the corresponding source:

https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/UsingClientSideEncryption.md

**Comment by aws-alan** [comment]
Source file has been fixed. 

https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/UsingClientSideEncryption.md will be refreshed shortly. 

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html will be refreshed by next week.
