### ISSUE TITLE
HTTP Referer example locks users out of bucket management

### ISSUE THREAD

**Issue by holmesjr** [awsdocs/amazon-s3-developer-guide#55]
The example at https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-4 will lock all users (including the root user) out of managing bucket policies etc if applied as-is. The docs should at least give a warning to this effect, or alternatively provide a better example that includes permissions for `s3:*` for the root user.

**Comment by joeholl** [comment]
Content has been updated
