### ISSUE TITLE
Missing code in Doc - Upload an Object Using the AWS SDK for .NET

### ISSUE THREAD

**Issue by Zer010** [awsdocs/amazon-s3-developer-guide#59]
`
            try
            {
                // 1. Put object-specify only key name for the new object.
                var putRequest1 = new PutObjectRequest
                {
                    BucketName = bucketName,
                    Key = keyName1,
                    ContentBody = "sample text"
                };

                PutObjectResponse response1 = await client.PutObjectAsync(putRequest1);

                // 2. Put the object-set ContentType and add metadata.
                var putRequest2 = new PutObjectRequest
                {
                    BucketName = bucketName,
                    Key = keyName2,
                    FilePath = filePath,
                    ContentType = "text/plain"
                };
                putRequest2.Metadata.Add("x-amz-meta-title", "someTitle");
            }`

The second put request `putRequest2.Metadata.Add("x-amz-meta-title", "someTitle");` is never called invoked with the client.

**Comment by aws-alan** [comment]
Could you provide more details? We've re-tested this code sample and it is working as expected.

**Comment by Zer010** [comment]
My apologies, in the demo the client does not perform the PUT.

PutObjectResponse response2 = await client.PutObjectAsync(putRequest2);

**Comment by aws-alan** [comment]
What is the source of the provided line: 
"PutObjectResponse response2 = await client.PutObjectAsync(putRequest2);" ?

The code example has been updated since opening this issue so perhaps this is an old issue?
https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/UploadObjSingleOpNET.md

**Comment by Zer010** [comment]
> What is the source of the provided line:
> "PutObjectResponse response2 = await client.PutObjectAsync(putRequest2);" ?
> 
> The code example has been updated since opening this issue so perhaps this is an old issue?
> https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/UploadObjSingleOpNET.md

In the demo does the metadata get updated to include "someTitle"? When I run it only put1 runs, put2 never does.

**Comment by aws-alan** [comment]
Example has been re-written and tested. Thank you for bringing this to our attention.
