### ISSUE TITLE
s3 not an option in policysim

### ISSUE THREAD

**Issue by nick-brady** [awsdocs/amazon-s3-developer-guide#63]
I found a very neat tool while searching for ways to debug why I'm failing to make request to an s3 bucket for a particular IAM user at https://policysim.aws.amazon.com/ here https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_testing-policies.html?icmpid=docs_iam_console

Unfortunately, when I tried to find "S3" as an option to test permissions (as done in the video even!) I saw the options stop after Route53 services.

After scrolling to the very bottom of the service options, this is where it stops.

<img width="512" alt="Screen Shot 2019-09-29 at 1 17 51 PM" src="https://user-images.githubusercontent.com/14315329/65831593-c39b3000-e2bb-11e9-88c6-bee1bb09f822.png">

**Comment by glenwinters** [comment]
@nick-brady The webpage doesn't handle small screen sizes well. S3 is in the next column of services to the right.

Here's what mine looks like:
![image](https://user-images.githubusercontent.com/435066/66757901-c3c23080-ee62-11e9-94eb-309b5161f2c7.png)

**Comment by nick-brady** [comment]
oh! I see. Thank you
