### ISSUE TITLE
S3 Select errors section is missing

### ISSUE THREAD

**Issue by ndabas** [awsdocs/amazon-s3-developer-guide#64]
https://docs.aws.amazon.com/AmazonS3/latest/dev/selecting-content-from-objects.html says:

> For a list of error codes and descriptions, see the [Special Errors](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html#RESTObjectSELECTContent-responses-special-errors) section of the SELECT Object Content page in the Amazon Simple Storage Service API Reference.

That link says:

> For a list of special errors for this operation, see [Selecting Content from Objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/selecting-content-from-objects.html).

So both documents are linking to each other for the errors section, but neither has the content.

**Comment by panjws** [comment]
This is now resolved. Thanks for flagging.
