### ISSUE TITLE
Restricting Access to Specific IP Addresses

### ISSUE THREAD

**Issue by mehtadman87** [awsdocs/amazon-s3-developer-guide#67]
The following statements are incorrect: 

"However, the request must not originate from the range of IP addresses specified in the condition."

"The condition in this statement identifies the 54.240.143.* range of disallowed Internet Protocol version 4 (IPv4) IP addresses."

The bucket policy evaluates to denying all actions from all users except those that originate from the range of IP addresses specified in the condition.

The condition in this statement identifies the 54.240.143.* range of ALLOWED Internet Protocol version 4 (IPv4) IP addresses."

**Comment by panjws** [comment]
This is now resolved. Thanks for flagging.
