### ISSUE TITLE
Impossible guidance given for granting access to root user

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/amazon-s3-developer-guide#71]
On the page https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html, under the section "Restricting Access to a Specific HTTP Referer", the second policy mentioned has a caution notice stating "Consider adding a third Sid that grants the root user s3:* actions.".  This is also located at https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/example-bucket-policies.md

This guidance is incorrect. First, I assume they mean Statement, not Sid, as you can't add any additional Sids. More importantly, no statement could be added that would grant access to the root user, because the deny in the second statement would take precedence.  You would instead need to replace `"Principal": "*"` with `"NotPrincipal": { "AWS": "arn:aws:iam::123456789012:root" }`.  Further, you cannot reference the root user specifically without also not denying access to all IAM principals in the account.

**Comment by rabilahiri** [comment]
Hi there. You're right that this guidance was erroneous. There were also other problems with that second policy, though, and we've removed it from the documentation altogether. Thanks for your feedback.
