### ISSUE TITLE
Typo in link to CloudTrail Data Event

### ISSUE THREAD

**Issue by brucezhang199083** [awsdocs/amazon-s3-developer-guide#72]
The doc says
> How Do I Enable Object-Level Logging for an S3 Bucket with **CloudWatch** Data Events?

However it's linked to CloudTrail Data Event page. Should change the link text to

`How Do I Enable Object-Level Logging for an S3 Bucket with CloudTrail Data Events?`

**Comment by panjws** [comment]
This is now resolved. Thanks for flagging.
