### ISSUE TITLE
Wildcards DO span resource ARN segments in policies

### ISSUE THREAD

**Issue by madmox** [awsdocs/amazon-s3-developer-guide#77]
The documentation on "[Specifying Resources in a Policy](https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/s3-arn-format.md)" states (also [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html)):

> You can use wildcards as part of the resource ARN. You can use wildcard characters (* and ?) within any ARN segment (the parts separated by colons). An asterisk (*) represents any combination of zero or more characters, and a question mark (?) represents any single character. You can use multiple * or ? characters in each segment, but **a wildcard cannot span segments**.

I checked in the [policy simulator](https://policysim.aws.amazon.com/) and the part on wildcards not spanning segments seems to be wrong.

Policy:
```json
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::my-bucket/foo/*/bar"
  }]
}
```
With the above policy, the user is granted access to `arn:aws:s3:::my-bucket/foo/1/2/bar`. So the wildcard DOES span ARN segments.

I believe this could lead to serious security issues in organization relying on the documented behavior. An example of such misconfiguration would be `arn:aws:s3:::my-bucket-*/public/*`. In this case, the policy matches `arn:aws:s3:::my-bucket-prod/private/public/*` - this is unexpected.

**Comment by madmox** [comment]
Also reported in [the IAM doc repo](https://github.com/awsdocs/iam-user-guide/issues/175).

**Comment by madmox** [comment]
> You can use wildcard characters (* and ?) within any ARN segment (**the parts separated by colons**).

I missed the bold part and assumed ann ARN segment was the same thing as an URI path segment (as ARN are URI).

**Comment by panjws** [comment]
Thanks. Based on the above and IAM repo [response](https://github.com/awsdocs/iam-user-guide/issues/175),  I will close this issue.
