### ISSUE TITLE
Does it support to set object lifetime as hours in object lifecycle rules 

### ISSUE THREAD

**Issue by yangwwii** [awsdocs/amazon-s3-developer-guide#97]
Hi,
Regrading to the object lifecycle rules, is it possible to set the lifetime of object into hours? 
such as, apply Expiration action to remove objects in bucket per hour, does it take effect?
<LifecycleConfiguration>
  <Rule>
    <ID>Expiration Rule</ID>
    <Filter>
       <Prefix>tax/</Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Expiration>
      _<Hours>1</Hours>_
    </Expiration>
  </Rule>
</LifecycleConfiguration>

I readed the page of https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/intro-lifecycle-rules.md, it is mentioned that, there are two kinds of rules below, does it only support to make the lifetime as midnight?  That's great to get your response, thanks.
1, Lifecycle rules: Based on an object's age
2. Lifecycle rules: Based on a specific date

**Comment by yangwwii** [comment]
Sorry for the incomplete info in the issue description.
Regrading to the object lifecycle rules, is it possible to set the lifetime of object into hours?
such as, apply Expiration action to remove objects in bucket per hour, does it take effect?
<Hours>1</Hours>

**Comment by yangwwii** [comment]
Sorry for the incomplete info in description. 
The attached is an example that I'm not sure whether it is a valid rule, or will it take effect in one hour?
![lifecycle example](https://user-images.githubusercontent.com/60733975/83707057-b523c600-a64b-11ea-9f0c-7d198f7ec012.PNG)

**Comment by aws-alan** [comment]
Hello,

Hours is not a valid tag here. I'm going to link our API guide which has some example json configuration which may be of use.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html
