### ISSUE TITLE
Google search for "s3 encryption at rest" gives output with incorrect default spelling

### ISSUE THREAD

**Issue by muktadadariya** [awsdocs/amazon-s3-developer-guide#98]
Google search for "s3 encryption at rest" gives output with incorrect default spelling. Instead of "default" it shows "cefault". 
Screenshot attached. 
[](https://www.google.com/search?client=firefox-b-e&q=s3+encyption+at+rest)

<img width="1119" alt="Screen Shot 2020-06-25 at 9 22 24 PM" src="https://user-images.githubusercontent.com/26233332/85810938-8f5d7e80-b72a-11ea-9463-8d4615d6cbf6.png">

**Comment by aws-alan** [comment]
Issue has been resolved.
